[package]
name = "marquage_derive"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
doc = false
proc-macro = true

[dependencies]
syn = {version = "2.0.117", features = ["extra-traits"]}
quote = "1.0.44"
proc-macro2 = "1.0.106"

convert_case = "0.11.0"
